# Generated by Django 4.1.2 on 2022-10-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransformerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transformer_Id', models.CharField(max_length=264)),
                ('Transformer_Date', models.CharField(max_length=264)),
                ('Transformer_Rating', models.CharField(max_length=264)),
                ('Transformer_PRating', models.CharField(max_length=264)),
                ('Transformer_SRating', models.CharField(max_length=264)),
                ('Transformer_Effi', models.CharField(max_length=264)),
            ],
        ),
    ]
